### ISSUE TITLE
Horus for Kodi is free software, pero no todo vale...

### ISSUE THREAD

**Issue by caperucitaferoz** [pepemebe/mag#1]
Por favor, antes de publicar cualquier modificacion de Horus, elimina mi nombre del archivo addon.xml y edita su descripcion, donde entre otras cosas pone claramente: **En Horus no vais a encontrar ningún tipo de contenido: ni películas, ni series ni eventos deportivos.**

Tambien es de agradecer que modifiques en el archivo default.py, el siguiente encabezado, donde me puedes citar como yo hice con los que me inspiraron, pero elimina tambien el nombre de mis colaboradores ya que nada tienen que ver contigo. 

```
 Horus by Caperucitaferoz based on previous work by:
 - Enen92 (https://github.com/enen92)
 - Joian (https://github.com/jonian)

 Thanks to those who have collaborated in any way, especially to:
 - @Canna_76
 - @AceStreamMOD (https://t.me/AceStreamMOD)
 - @luisma66 (tester raspberry)

 This file is part of Horus for Kodi

 Horus for Kodi is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by caperucitaferoz** [comment]
ok,
Aunque si las modificaciones consisten en añadir una lista,  yo te suguiero crear un addon nuevo q utilice Horus para reproducir. Tienes informacion en https://telegra.ph/Horus-04-25 y me puedes encontrar en https://t.me/kodiadictosssgrupo si necesitas soporte.

**Comment by pepemebe** [comment]
Gracias.
