### ISSUE TITLE
Tacones

### ISSUE THREAD

**Issue by SomeoneLikeYou462** [pepemebe/mag#2]
Hola, desde el equipo de desarrollo de Tacones le pediríamos que eliminara cualquier contenido de nuestro proyecto en el suyo, consideramos que Tacones ya es un addon muy completo y no hace falta realizar forks ni que usen nuestra DB para otros proyectos.

_Someone Like You, La mala de la Novela y equipo de desarrollo de Tacones_

**Comment by pepemebe** [comment]
Hola, he limpiado el contenido que hacía referencia a _Tacones_, así como las _BBDD_ que aparecían en este repositorio.
También he eliminado los _scripts python_ de los _zip_.

He de reconocer que el _addon_ ha mejorado mucho y algunas de las razones que me llevaron a crear el script ya no tienen razón de ser.

También quiero mencionar la licencia **GNU GPL 3.0** con la que se distribuye _Tacones_, ya que en todo momento he mencionado el origen _(La Mala De La Novela - TACONES)_ y cumplido con ella.

_pepemebe_
